FROM n8nio/n8n:2.0.3
WORKDIR /home/node/.n8n
ENV DB_TYPE=postgres
ENV GENERIC_TIMEZONE=Europe/Madrid
ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
ENV N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
EXPOSE 5678