name: Backup n8n prod volume

on:
  schedule:
    - cron: "45 19 * * 0"  # Domingos 21:45 Europe/Madrid ≈ 19:45 UTC (ajusta si quieres otra hora)
  workflow_dispatch: {}

jobs:
  backup:
    runs-on: ubuntu-latest
    concurrency:
      group: backup-running-coach-n8n-prod
      cancel-in-progress: true
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      FLY_APP: running-coach-n8n
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Create tar inside VM
        run: |
          flyctl ssh console -a "$FLY_APP" -C 'tar czf /tmp/n8n_backup_$(date +%F).tar.gz -C /home/node .n8n && ls -lh /tmp/n8n_backup_*.tar.gz'

      - name: Download backup
        run: flyctl sftp get "/tmp/n8n_backup_$(date +%F).tar.gz" -a "$FLY_APP"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: n8n-backup-${{ github.run_id }}
          path: n8n_backup_*.tar.gz
          retention-days: 30
