name: CI - Validate n8n workflows

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verifica secreto N8N_ENCRYPTION_KEY
        run: |
          if [ -z "${{ secrets.N8N_ENCRYPTION_KEY }}" ]; then
            echo "❌ Falta GitHub Secret N8N_ENCRYPTION_KEY"
            exit 1
          fi

      - name: Levanta n8n efímero
        env:
          N8N_ENCRYPTION_KEY: ${{ secrets.N8N_ENCRYPTION_KEY }}
        run: |
          set -e
          docker run -d --name n8n-ci \
            -p 5678:5678 \
            -e N8N_LISTEN_ADDRESS=0.0.0.0 \
            -e N8N_PORT=5678 \
            -e N8N_BASIC_AUTH_ACTIVE=false \
            -e GENERIC_TIMEZONE=Europe/Madrid \
            -e N8N_ENCRYPTION_KEY="$N8N_ENCRYPTION_KEY" \
            n8nio/n8n:1.78.1

          # Espera a que responda (mejor /rest/health que /)
          for i in $(seq 1 150); do
            if curl -fsS http://localhost:5678/rest/health | grep -q '"status":"ok"'; then
              echo "✅ n8n up"
              break
            fi
            if [ $((i%10)) -eq 0 ]; then
              echo "⏳ still waiting... ($i)"
              docker logs --tail 80 n8n-ci || true
            fi
            sleep 2
          done

      - name: Importa workflows del repo (si hay)
        run: |
          set -e
          docker exec n8n-ci sh -lc 'mkdir -p /home/node/import'
          # Copia desde el runner al contenedor (si existe la carpeta)
          if [ -d "workflows" ]; then
            docker cp workflows/. n8n-ci:/home/node/import/ || true
          fi
          # POSIX: comprueba si hay *.json
          docker exec n8n-ci sh -lc '
            set -- /home/node/import/*.json
            if [ -e "$1" ]; then
              echo "🛬 Importando workflows..."
              n8n import:workflow --input "/home/node/import/*.json"
              echo "📋 Listado:"
              n8n list:workflow || true
            else
              echo "ℹ️ No hay workflows/*.json que importar"
            fi
          '

      - name: Tear down
        if: always()
        run: |
          docker logs --tail 200 n8n-ci || true
          docker rm -f n8n-ci || true
