name: CI - Validate n8n workflows

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verifica secreto N8N_ENCRYPTION_KEY
        run: |
          if [ -z "${{ secrets.N8N_ENCRYPTION_KEY }}" ]; then
            echo "❌ Falta GitHub Secret N8N_ENCRYPTION_KEY"
            exit 1
          fi

      - name: Levanta n8n efímero
        env:
          N8N_ENCRYPTION_KEY: ${{ secrets.N8N_ENCRYPTION_KEY }}
        run: |
          docker run -d --name n8n-ci \
            -p 5678:5678 \
            -e N8N_LISTEN_ADDRESS=0.0.0.0 \
            -e N8N_PORT=5678 \
            -e N8N_BASIC_AUTH_ACTIVE=false \
            -e GENERIC_TIMEZONE=Europe/Madrid \
            -e N8N_ENCRYPTION_KEY="$N8N_ENCRYPTION_KEY" \
            n8nio/n8n:1.78.1

          for i in {1..150}; do
            if curl -fsS http://localhost:5678/ >/dev/null; then
              echo "✅ n8n up"
              break
            fi
            sleep 2
          done

      - name: Importa workflows del repo
        run: |
          docker exec n8n-ci bash -lc 'mkdir -p /home/node/import'
          docker cp workflows/. n8n-ci:/home/node/import/ || true
          docker exec n8n-ci bash -lc 'shopt -s nullglob; FILES=(/home/node/import/*.json); \
            [ ${#FILES[@]} -eq 0 ] && echo "No hay workflows/*.json" || n8n import:workflow --input "/home/node/import/*.json"'

      - name: Lista workflows importados
        run: docker exec n8n-ci bash -lc 'n8n list:workflow || true'

      - name: Tear down
        if: always()
        run: |
          docker logs --tail 200 n8n-ci || true
          docker rm -f n8n-ci || true
