name: CI - Validate n8n workflows

on:
  push:
    branches: [ main ]
    paths:
      - "workflows/**.json"
  pull_request:
    paths:
      - "workflows/**.json"

jobs:
  validate:
    runs-on: ubuntu-latest

    env:
      N8N_IMAGE: n8nio/n8n:1.78.1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verifica secreto N8N_ENCRYPTION_KEY
        run: |
          set -e
          if [ -z "${{ secrets.N8N_ENCRYPTION_KEY }}" ]; then
            echo "❌ Falta GitHub Secret N8N_ENCRYPTION_KEY"
            exit 1
          fi

      - name: Levanta n8n efímero
        run: |
          set -e
          docker run -d --name n8n-ci \
            -p 5678:5678 \
            -e N8N_LISTEN_ADDRESS="0.0.0.0" \
            -e N8N_PORT="5678" \
            -e N8N_BASIC_AUTH_ACTIVE="false" \
            -e N8N_ENCRYPTION_KEY="${{ secrets.N8N_ENCRYPTION_KEY }}" \
            -e GENERIC_TIMEZONE="Europe/Madrid" \
            $N8N_IMAGE

          # Espera
          for i in {1..150}; do
            if curl -fsS http://localhost:5678/ >/dev/null; then
              echo "✅ n8n up"
              break
            fi
            if [ $((i%10)) -eq 0 ]; then
              echo "⏳ still waiting... ($i)"
              docker logs --tail 80 n8n-ci || true
            fi
            sleep 2
          done

      - name: Importa workflows (desde el repo)
        run: |
          set -e
          # Copiamos los JSON al contenedor y ejecutamos el CLI dentro
          docker exec n8n-ci bash -lc 'mkdir -p /home/node/import'
          docker cp ./workflows/. n8n-ci:/home/node/import/
          docker exec n8n-ci bash -lc 'n8n import:workflow --input "/home/node/import/*.json"'

      - name: Lista workflows importados
        run: |
          docker exec n8n-ci bash -lc 'n8n list:workflow'

      - name: Tear down
        if: always()
        run: |
          docker logs --tail 200 n8n-ci || true
          docker rm -f n8n-ci || true
