name: Deploy n8n on Fly

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GENERIC_TIMEZONE: "Europe/Madrid"
      DB_TYPE: "postgres"

      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      INTERVALS_ICU_ATHLETE_ID: ${{ secrets.INTERVALS_ICU_ATHLETE_ID }}
      INTERVALS_ICU_BASIC_AUTH: ${{ secrets.INTERVALS_ICU_BASIC_AUTH }}
      N8N_BASIC_AUTH_USER: ${{ secrets.N8N_BASIC_AUTH_USER }}
      N8N_BASIC_AUTH_PASSWORD: ${{ secrets.N8N_BASIC_AUTH_PASSWORD }}
      N8N_ENCRYPTION_KEY: ${{ secrets.N8N_ENCRYPTION_KEY }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node & n8n CLI
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g n8n

      - name: Install Fly CLI
        uses: superfly/flyctl-actions@v1
        with:
          version: '1.4.0'

      - name: Deploy to Fly
        run: flyctl deploy --config fly.toml --remote-only

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Import n8n workflows
        run: |
          HOST=$(flyctl info --json | jq -r '.Hostname')
          export N8N_HOST=$HOST
          export N8N_PROTOCOL=https
          n8n import:workflow --input=workflows/*.json