name: Deploy n8n to Fly.io

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  APP: running-coach-n8n

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Comprobar secrets requeridos
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          N8N_ENCRYPTION_KEY: ${{ secrets.N8N_ENCRYPTION_KEY }}
        run: |
          [ -z "${FLY_API_TOKEN:-}" ] && { echo "❌ Falta FLY_API_TOKEN"; exit 1; }
          [ -z "${N8N_ENCRYPTION_KEY:-}" ] && { echo "❌ Falta N8N_ENCRYPTION_KEY"; exit 1; }
          echo "✅ Secrets presentes"

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Verificar autenticación
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl auth whoami

      - name: Actualizar secret N8N_ENCRYPTION_KEY en Fly
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          N8N_ENCRYPTION_KEY: ${{ secrets.N8N_ENCRYPTION_KEY }}
        run: |
          flyctl secrets set N8N_ENCRYPTION_KEY="$N8N_ENCRYPTION_KEY" --app "$APP" --stage

      - name: Deploy a Fly
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy --app "$APP" --remote-only --yes

      - name: Estado y últimas releases
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl status --app "$APP"
          flyctl releases --app "$APP" --limit 5
